---
title: "Finance Project Bank"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xml2)
library(tidyverse)
library(rvest)
library(knitr)
library(kableExtra)
```

```{r cars, echo = FALSE}
#Create a list with all html project names
filelist = list.files(pattern = "project_*.*.html")
# create df to hold data
df = tibble(Project = character(length(filelist)),
            'Project Status' = character(length(filelist)),
            Priority = character(length(filelist)),
            'Required departments' = character(length(filelist)),
            'Expected cost' = character(length(filelist)),
            'Projected approved by' = character(length(filelist)),
            'Budget approved by' = character(length(filelist)),
            ID = double(length(filelist))
            )

for (i in 1:length(filelist)) {
  data = read_html(filelist[i])
  #fill the df
  df$Project[i] = paste0("[", str_remove(str_remove(str_remove(html_text(xml_child(xml_child(xml_child(data, 2), 2), 3)),pattern = "\nArticle\\s[0-9]"),pattern = "\n\n\n\n"),pattern = "\n\n"), "](", filelist[i], ")")
    
  df$`Required departments`[i] =  str_remove(xml_child(xml_child(xml_child(data, 2), 2), 6) %>% 
                                  html_text() %>% 
                                  str_remove_all(pattern = "\nArticle\\s[0-9]"), "Required departments ")
  
  df$`Project Status`[i] =        str_remove(xml_child(xml_child(xml_child(data, 2), 2), 11) %>% 
                                  html_text() %>% 
                                  str_remove_all(pattern = "\nArticle\\s[0-9]"), "Project Status ")
  
  df$Priority[i] =                str_remove(xml_child(xml_child(xml_child(data, 2), 2), 9) %>% 
                                  html_text() %>% 
                                  str_remove_all(pattern = "\nArticle\\s[0-9]"), "Priority  ")
  
  df$`Expected cost`[i] =         str_remove(xml_child(xml_child(xml_child(data, 2), 2), 8) %>% 
                                  html_text() %>% 
                                  str_remove_all(pattern = "\nArticle\\s[0-9]"), "Expected cost ")
  
  df$`Projected approved by`[i] = str_remove(xml_child(xml_child(xml_child(data, 2), 2), 7) %>% 
                                  html_text() %>% 
                                  str_remove_all(pattern = "\nArticle\\s[0-9]"), "Project approved by ")
  
  df$`Budget approved by`[i] =    str_remove(xml_child(xml_child(xml_child(data, 2), 2), 10) %>% 
                                  html_text() %>% 
                                  str_remove_all(pattern = "\nArticle\\s[0-9]"), "Budget approved by ")
  df$ID[i] = as.integer(str_remove(str_remove(filelist[i], pattern = "project_"), pattern = ".html"))
}
df[with(df,order(df$Project)),] %>%
  filter(df$`Project Status` != "\n  Completed\n") %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

